### ISSUE TITLE
Remove HEADSCALE_SQLITE_PATH ?

### ISSUE THREAD

**Issue by Silex** [reyzzz/quasaScale-backend#2]
Hello,

It is my understanding that if you really use HEADSCALE_API_URL for everything, then HEADSCALE_SQLITE_PATH is not necessary.

But I just noticed in the code that you actually use both. Is it planned to use the API only?

Same for HEADSCALE_ACL_PATH, I don't use the `.huson` file, they're stored in DB but QuasaScale forces me to use the `.hujson` file. I'd be nice to support both workflows.

I'm currently giving it a try but these are my first impressions, many more issues/PR should follow 😁

**Comment by reyzzz** [comment]
Hello Silex,

Thank you for giving it a try.
As for the issue, indeed we need HEADSCALE_SQLITE_PATH because using quasascale backend you are able to change the IP address and this can only be achieved by querying the database directly.

As for the HEADSCALE_ACL_PATH, quasascale backend also manipulate this file directly without going through headscale api because we try to keep the comments in the .hujson file.

I can add support for ACL in the database.
